name: mutable_model
description: A solution for Flutter state management based on mutable objects and mutable collections.
version: 0.3.0
author: Alexander Ryzhov <aryzhov07@gmail.com>
homepage: https://github.com/aryzhov/flutter-mutable-model

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
